"""Render a validated workflow spec as readable Claude Workflow JavaScript."""

from __future__ import annotations

import json
from pathlib import Path

from ..config import Config
from ..workflow_spec import WorkflowSpec


SCHEMAS = {
    "scope": {"type": "object", "properties": {"status": {"enum": ["done", "blocked", "needs_decision"]}, "summary": {"type": "string"}, "files_changed": {"type": "array", "items": {"type": "string"}}, "notes": {"type": "string"}}, "required": ["status", "summary", "files_changed", "notes"]},
    "dev": {"type": "object", "properties": {"status": {"enum": ["done", "blocked", "needs_decision"]}, "summary": {"type": "string"}, "files_changed": {"type": "array", "items": {"type": "string"}}, "tests_run": {"type": "array", "items": {"type": "string"}}, "notes": {"type": "string"}}, "required": ["status", "summary", "files_changed", "tests_run", "notes"]},
    "redteam": {"type": "object", "properties": {"status": {"enum": ["all_passed", "failures_found", "blocked", "needs_decision"]}, "summary": {"type": "string"}, "files_changed": {"type": "array", "items": {"type": "string"}}, "failures_found": {"type": "array", "items": {"type": "string"}}, "notes": {"type": "string"}}, "required": ["status", "summary", "files_changed", "failures_found", "notes"]},
    "review": {"type": "object", "properties": {"accepted": {"type": "boolean"}, "summary": {"type": "string"}, "findings": {"type": "array", "items": {"type": "string"}}, "notes": {"type": "string"}}, "required": ["accepted", "summary", "findings", "notes"]},
    "commit": {"type": "object", "properties": {"status": {"enum": ["done", "blocked", "needs_decision"]}, "summary": {"type": "string"}, "notes": {"type": "string"}}, "required": ["status", "summary", "notes"]},
}


def _json(value: object) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False)


def render_claude_workflow(config: Config, config_path: Path, spec: WorkflowSpec) -> str:
    project_root = config_path.resolve().parent
    repo = str(Path(config.repo).expanduser().resolve())
    static_context = {
        "project": config.project,
        "repo": repo,
        "projectFolder": str(project_root),
        "projectSpecPath": str(project_root / "spec" / "project.spec.md"),
        "invariantsPath": str(project_root / "spec" / "invariants.yaml"),
        "gatesPath": str(project_root / "spec" / "gates.yaml"),
        "checkpointScriptPath": str(project_root / "scripts" / "checkpoint_commit.sh"),
    }
    stages = {
        name: {
            "description": stage.description,
            "steps": [
                {"id": step.id, "title": step.title, "model": step.model, "effort": step.effort,
                 "phases": step.phases, "prompt": step.prompt}
                for step in stage.steps
            ],
        }
        for name, stage in spec.stages.items()
    }
    return f'''// Generated by aiwk. Edit workflow.yaml, then render again.
export const meta = {_json({"project": spec.project, "description": spec.description, "defaultStage": spec.default_stage})};

const staticContext = {_json(static_context)};
const stages = {_json(stages)};
const schemas = {_json(SCHEMAS)};

function normalizedArgs(args = {{}}) {{
  return {{
    stage: args.stage || meta.defaultStage,
    fromStep: args.fromStep || null,
    onlyStep: args.onlyStep || null,
    preflightSummary: args.preflightSummary || "",
    handoffPath: args.handoffPath || "",
    beadsSnapshot: args.beadsSnapshot || "",
  }};
}}

function selectSteps(args) {{
  const selectedStage = stages[args.stage];
  if (!selectedStage) throw new Error(`Unknown stage: ${{args.stage}}`);
  if (args.onlyStep && args.fromStep) throw new Error("onlyStep and fromStep cannot be used together");
  if (args.onlyStep) {{
    const step = selectedStage.steps.find((candidate) => candidate.id === args.onlyStep);
    if (!step) throw new Error(`Unknown onlyStep '${{args.onlyStep}}' in stage '${{args.stage}}'`);
    return [step];
  }}
  if (args.fromStep) {{
    const index = selectedStage.steps.findIndex((candidate) => candidate.id === args.fromStep);
    if (index < 0) throw new Error(`Unknown fromStep '${{args.fromStep}}' in stage '${{args.stage}}'`);
    return selectedStage.steps.slice(index);
  }}
  return selectedStage.steps;
}}

function phasePrompt(step, phase, args) {{
  if (phase === "commit") {{
    return `Checkpoint step ${{step.id}}. Run exactly:\ncd ${{staticContext.repo}}\nbash ${{staticContext.checkpointScriptPath}} ${{step.id}}`;
  }}
  return `Project: ${{staticContext.project}}
Repository: ${{staticContext.repo}}
Project folder: ${{staticContext.projectFolder}}
Project spec: ${{staticContext.projectSpecPath}}
Invariants: ${{staticContext.invariantsPath}}
Gates: ${{staticContext.gatesPath}}
Preflight summary: ${{args.preflightSummary || "not provided"}}
Handoff path: ${{args.handoffPath || "not provided"}}
Beads snapshot: ${{args.beadsSnapshot || "not provided"}}

Read the relevant spec, invariants, and gates before editing. Use repository files as source of truth.
Use the supplied preflight summary; do not rerun broad preflight unless it is stale or contradicted.
Use the handoff path when provided. Keep scope tight to this step and phase.

Step ${{step.id}} — ${{step.title}}
Phase: ${{phase}}
Task: ${{step.prompt[phase]}}`;
}}

export default async function workflow(rawArgs = {{}}) {{
  const args = normalizedArgs(rawArgs);
  const results = [];
  let steps;
  try {{
    steps = selectSteps(args);
  }} catch (error) {{
    return JSON.stringify({{ halted_at: "selection", reason: error.message, stage: args.stage, results }});
  }}
  for (const step of steps) {{
    for (const phase of step.phases) {{
      const result = await agent({{
        model: step.model,
        effort: step.effort,
        prompt: phasePrompt(step, phase, args),
        schema: schemas[phase],
      }});
      results.push({{ step: step.id, phase, result }});
      const blocked = result.status === "blocked" || result.status === "needs_decision";
      const rejected = phase === "review" && result.accepted === false;
      const failures = phase === "redteam" && result.status === "failures_found";
      if (blocked || rejected || failures) {{
        return JSON.stringify({{ halted_at: `${{step.id}}:${{phase}}`, reason: result.status || "review_rejected", stage: args.stage, results }});
      }}
    }}
  }}
  return JSON.stringify({{ halted_at: null, reason: "completed", stage: args.stage, results }});
}}
'''

