from pathlib import Path
import tempfile
import unittest

from aiwk.cli import initialize
from aiwk.render import render


class CoordinatorPromptTests(unittest.TestCase):
    def test_init_generates_thin_launch_runbook(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            repo = root / "repo"
            repo.mkdir()
            result = initialize("demo", str(repo), str(root / ".aiwk"), "generic")
            path = Path(result["coordinator_path"])
            text = path.read_text(encoding="utf-8")
            self.assertEqual(path.name, "master_coordinator_prompt.md")
            for marker in (
                "Generated by AIWK", "Durable authority", "GENERIC_SS0",
                "aiwk render claude-workflow", "aiwk preflight", "aiwk context-pack",
                "exact compact JSON", "all_steps_accepted", "Never set both",
            ):
                self.assertIn(marker, text)
            self.assertIn(str(repo.resolve()), text)

    def test_render_refreshes_coordinator_and_includes_enabled_beads_commands(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            repo = root / "repo"
            repo.mkdir()
            initialized = initialize("demo", str(repo), str(root / ".aiwk"), "generic")
            config = Path(initialized["config_path"])
            workflow = config.parent / "workflow.yaml"
            text = workflow.read_text(encoding="utf-8")
            beads = '''beads:
  enabled: true
  before_edit_commands:
    - bd prime || true
    - bd list --status open,in_progress || true

'''
            workflow.write_text(
                text.replace("stages:\n", beads + "stages:\n", 1).replace("GENERIC_SS0", "CUSTOM_SS0"),
                encoding="utf-8",
            )
            result = render(config)
            coordinator = Path(result["coordinator_path"]).read_text(encoding="utf-8")
            self.assertIn("CUSTOM_SS0", coordinator)
            self.assertNotIn("GENERIC_SS0", coordinator)
            self.assertIn("bd prime || true", coordinator)
            self.assertIn("exact combined output", coordinator)

