"""Generate a thin operator/coordinator launch prompt from durable AIWK inputs."""

from __future__ import annotations

import json
from pathlib import Path
import shlex
import sys

from .config import Config
from .workflow_spec import WorkflowSpec


def coordinator_prompt(
    config: Config,
    config_path: Path,
    workflow_spec_path: Path,
    generated_js_path: Path,
    spec: WorkflowSpec,
) -> str:
    project_root = config_path.resolve().parent
    repo = Path(config.repo).expanduser().resolve()
    python = shlex.quote(sys.executable)
    config_arg = shlex.quote(str(config_path.resolve()))
    workflow_arg = shlex.quote(str(workflow_spec_path.resolve()))
    output_arg = shlex.quote(str(generated_js_path.resolve()))
    default_stage = spec.default_stage
    default_steps = [step.id for step in spec.stages[default_stage].steps]
    handoff_path = project_root / "state" / "COORDINATOR_PRESTART_handoff.md"
    preflight_path = project_root / "state" / "coordinator_preflight.json"
    beads_snapshot_path = project_root / "state" / "coordinator_beads_snapshot.txt"
    stage_lines = []
    for stage_name, stage in spec.stages.items():
        stage_lines.append(f"- `{stage_name}`: " + ", ".join(f"`{step.id}`" for step in stage.steps))
    beads_value = ""
    beads_context_option = ""
    beads_block = "Beads is disabled. Use an empty `beadsSnapshot`; do not require or invent `bd` commands."
    if spec.beads.enabled:
        commands = spec.beads.before_edit_commands or [
            "bd prime || true",
            f"bd list --status {spec.beads.status_filter} || true",
        ]
        rendered = "\n".join(f"  {command}" for command in commands)
        beads_value = f"<replace with exact contents of {beads_snapshot_path}>"
        beads_context_option = f" --beads-snapshot-file {shlex.quote(str(beads_snapshot_path))}"
        beads_block = (
            "Beads is enabled. Run the configured commands and persist their exact combined output:\n\n"
            "```bash\n"
            f"cd {shlex.quote(str(repo))}\n{{\n{rendered}\n}} 2>&1 | tee {shlex.quote(str(beads_snapshot_path))}\n"
            "```\n\n"
            f"Use the exact contents of `{beads_snapshot_path}`—not a phrase such as “use fresh Beads state”—as `beadsSnapshot`."
        )
    args = {
        "stage": default_stage,
        "fromStep": None,
        "onlyStep": None,
        "preflightSummary": f"<replace with exact JSON from {preflight_path}>",
        "handoffPath": str(handoff_path),
        "beadsSnapshot": beads_value,
    }
    commit = spec.commit
    return f"""# AIWK Master Coordinator Prompt: {config.project}

> Generated by AIWK. Do not store project requirements here. Edit `workflow.yaml` and the files under `spec/`, then rerender. This file is a launch runbook; durable source/spec files remain authoritative.

## Mission

Coordinate and launch the generated AIWK workflow for `{config.project}` against the target repository. Do not independently redesign the task or orchestrate substitute role loops; the generated workflow owns Scope, Developer, Red Team, Objective Gate, Reviewer, and Commit routing.

## Exact paths

- Target repository: `{repo}`
- AIWK config: `{config_path.resolve()}`
- Workflow source: `{workflow_spec_path.resolve()}`
- Project spec: `{project_root / 'spec' / 'project.spec.md'}`
- Invariants: `{project_root / 'spec' / 'invariants.yaml'}`
- Semantic gates: `{project_root / 'spec' / 'gates.yaml'}`
- Generated workflow: `{generated_js_path.resolve()}`
- State directory: `{project_root / 'state'}`
- Logs directory: `{project_root / 'logs'}`

## Durable authority

Before doing anything else, read the workflow source, project spec, invariants, and semantic gates listed above. Treat them and the target repository as authoritative. This coordinator prompt must not override them. If this runbook conflicts with committed source or those durable files, stop and report the conflict.

If the project spec contains a Prerequisites section, verify every prerequisite from committed repository state, Git history, or durable AIWK evidence. Do not rely on transcript memory or a bare assertion that prerequisite work was completed. Stop with the exact missing prerequisite and evidence checked if verification fails.

Configured stages and steps:

{chr(10).join(stage_lines)}

The default full run is stage `{default_stage}` in this order: {', '.join(default_steps)}.

## Pre-launch procedure

Run these exact commands from any directory. Preserve their compact JSON output.

1. Rerender from the durable inputs so the execution artifact and this coordinator runbook are fresh:

   ```bash
   {python} -m aiwk render claude-workflow --config {config_arg} --workflow-spec {workflow_arg} --out {output_arg}
   ```

2. Run fresh preflight:

   ```bash
   {python} -m aiwk preflight --config {config_arg} | tee {shlex.quote(str(preflight_path))}
   ```

   Confirm `{preflight_path}` contains the exact compact JSON and use that content as `preflightSummary`. If `dirty_relevant` is true, inspect the referenced log and stop when changes are unrelated, unexplained, or unsafe for commit mode `{commit.mode}`. Never clean, reset, stage, or discard user work merely to make preflight green.

3. Complete the Beads/operator-context procedure below. When Beads is enabled, do not continue until `{beads_snapshot_path}` exists and contains the captured command output.

4. Create a durable prestart context pack after operator context has been collected:

   ```bash
   {python} -m aiwk context-pack --config {config_arg} --phase COORDINATOR_PRESTART --include-diff --max-diff-lines 80{beads_context_option}
   ```

   Confirm the handoff exists at `{handoff_path}` and use that exact path as `handoffPath`. If it links older objective-gate evidence, treat that evidence as historical context only; the launched workflow must produce fresh evidence for its own attempts.

5. Syntax-check the generated JavaScript when Node is available:

   ```bash
   node --check {output_arg}
   ```

   If Node is unavailable, report that fact; do not edit generated JavaScript to work around it.

## Beads/operator context

{beads_block}

## Runtime request

Launch the generated workflow at `{generated_js_path.resolve()}` with this argument shape after replacing the marked values with the exact fresh outputs collected above:

```json
{json.dumps(args, indent=2)}
```

For a full run, leave `fromStep` and `onlyStep` null. To resume accepted work, set `fromStep` explicitly. To isolate one step, set `onlyStep` explicitly. Never set both. Do not infer a resume point without durable evidence that earlier steps were accepted.

## Coordination and halt policy

- Let the generated workflow own all role sequencing and bounded retry loops.
- Do not bypass or reinterpret objective gate return codes, timeout flags, check thresholds, evidence paths, or integrity metadata.
- Reviewer acceptance is necessary but cannot override a red objective gate.
- Commit mode is `{commit.mode}`. Verify the reviewer has rejected unrelated dirtiness before an active commit mode runs.
- Halt and report the exact `halted_at`, `reason`, role output, gate evidence path, and gate log path when the workflow stops.
- Do not expand scope, waive prerequisites, rewrite durable boundaries, run excluded live/destructive tests, or rebase/restack branches unless the durable project files explicitly authorize it.

## Completion checks

After the workflow returns:

1. Require final `reason` to be `all_steps_accepted` for a successful full run.
2. Inspect each step result’s gate, review, and commit fields.
3. Verify every objective gate evidence/log path exists and `gate_clean` is true.
4. For active commit modes, verify the commit result reports an acceptable status and clean final tree.
5. Run `git -C {shlex.quote(str(repo))} status --short` and report any remaining changes without modifying them.
6. Produce a final context pack before handing work to another operator or agent.
"""


def write_coordinator_prompt(
    config: Config,
    config_path: Path,
    workflow_spec_path: Path,
    generated_js_path: Path,
    spec: WorkflowSpec,
) -> Path:
    output = config_path.resolve().parent / "master_coordinator_prompt.md"
    output.write_text(
        coordinator_prompt(config, config_path, workflow_spec_path, generated_js_path, spec),
        encoding="utf-8",
    )
    return output
